config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies, :subjects, :courses, :languages
  post 'subjects/new',to: 'subjects#create'
  post 'courses/new',to: 'courses#create'
  post 'companies/new',to: 'companies#create'
  post 'languages/new',to: 'languages#create'
  get "/:page" => "static#show"

  root 'subjects#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :courses
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  include PgSearch
  has_many :courses
  validates :name, presence: true
  #validates :rank, numericality: { only_integer: true, greater_than: 0}
  pg_search_scope :search_by_name, against: [:name, :organization_name]
end

app/models/course.rb
class Course < ApplicationRecord
  include PgSearch
  validates :name, presence: true
  validates :info, presence: true
  validates :info, length: {minimum: 15}
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  #validates :rating, numericality: {  greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  belongs_to :company
  belongs_to :subject
  has_and_belongs_to_many :languages
  pg_search_scope :search_by_name, against: [:name]
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
end

app/models/subject.rb
class Subject < ApplicationRecord
  include PgSearch
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
  has_many :courses
  has_attached_file :avatar, styles: { default: "350x300>",logo: "50x50"}, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  pg_search_scope :search_by_name, against: [:name]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new
    @category.name = params[:category][:name]
    @category.save

    if @category.errors.any?
      render :new
    else
      redirect_to root_path
    end
  end

  def new
    @category = Category.new
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index]
  def create
    @company = Company.new(company_params)
    @company.save
    if @company.errors.any?
      render :'companies/new'
    else
      redirect_to @company
    end
  end

  def new
    @company = Company.new
  end
  def index
    if params[:q] != nil
      @companies = Company.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
    else
      @companies = Company.all.paginate(:page => params[:page],per_page:4)
    end
  end
  def show
    @company = Company.find_by(id: params[:id])
    @company_courses = Course.where(company_id: [@company.id])
    if @company.nil?
      redirect_to root_path
    end
  end
  def edit
    @company = Company.find(params[:id])
  end
  def update
    @company = Company.update(params[:id],company_params)
    @company.save
    if @company.errors.any?
      render 'edit'
    else
      redirect_to company_path
    end
  end
  def delete
    @company = Company.find(params[:id])
  end
  def destroy
    Company.find(params[:id]).destroy
    redirect_to companies_path
  end
  private
    def company_params
      params.require(:company).permit(:name,:foundation_year,:description,:phone,:email,:organization_name,:website)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index]
  def create
    @course = Course.new(course_params)
    @course.save
    if @course.errors.any?
      render :'courses/new'
    else
      redirect_to @course
    end
  end

  def new
    @course = Course.new
  end
  def index
    if params[:q]
      @courses = Course.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
    else
      @courses = Course.all.paginate(:page => params[:page],per_page:1)
    end
  end
  def show
    @course = Course.find_by(id: params[:id])
    if @course.nil?
      redirect_to courses_path
    end
  end
  def edit
    @course = Course.find(params[:id])
  end
  def update
    @course = Course.update(params[:id],course_params)
    @course.save
    if @course.errors.any?
      render 'edit'
    else
      redirect_to course_path
    end
  end
  def delete
    @course = Course.find(params[:id])
  end
  def destroy
    Course.find(params[:id]).destroy
    redirect_to courses_path
  end
  private
    def course_params
    params.require(:course).permit(:name,:info,:price,:total_lessons,:company_id,:subject_id,:language_ids)
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
  end
  def create
    @language = Language.new(language_params)
    @language.save
    if @language.errors.any?
      render :'languages/new'
    else
      redirect_to @language
    end
  end
  def new
    @language = Language.new
  end
  def show
    @language = Language.find_by(id: params[:id])
    if @language.nil?
      redirect_to languages_path
    end
  end
  def edit
    @language = Language.find(params[:id])
  end
  def update
    @language = Language.update(params[:id],language_params)
    @language.save
    if @language.errors.any?
      render 'edit'
    else
      redirect_to language_path
    end
  end
  def delete
    @language = Language.find(params[:id])
  end
  def destroy
    Language.find(params[:id]).destroy
    redirect_to languages_path
  end
  private
    def language_params
      params.require(:language).permit(:name,:description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index,:home]
    def create
      @subject = Subject.new(subject_params)
      @subject.save
      if @subject.errors.any?
        render 'new'
      else
        redirect_to @subject
      end
    end

    def new
      @subject = Subject.new
    end
    def index
      if params[:q] != nil
        @subjects = Subject.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
      else
        @subjects = Subject.all.paginate(:page => params[:page],per_page:1)
      end
    end
    def show
      @subject = Subject.find_by(id: params[:id])
      @subject_courses = Course.where(subject_id: [@subject.id])
      if @subject.nil?
        redirect_to root_path
      end
    end
    def edit
      @subject = Subject.find(params[:id])
    end
    def update
      @subject = Subject.update(params[:id],subject_params)
      @subject.save
      if @subject.errors.any?
        render 'edit'
      else
        redirect_to subjects_path
      end
    end
    def delete
      @subject = Subject.find(params[:id])
    end
    def destroy
      Subject.find(params[:id]).destroy
      redirect_to subjects_path
    end
    private
      def subject_params
      params.require(:subject).permit(:avatar,:name,:description)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/categories/new.html.erb
<% content_for(:title) { 'Новая категория' } %>

<%= form_for @category, html: { class: 'form' } do |form| %>
  <label>
    <span class="form__label-text">
      Название <%= required_field %>
    </span>

    <%= form.text_field :name %>
  </label>

  <%= form.submit 'Готово' %>
<% end %>

app/views/companies/edit.html.erb
<div class="form-style-8">
  <h2>Редактировать компанию</h2>
  <%= form_for(@company) do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Год основания<%= form.text_field :foundation_year %></p>
    <p>Описание<%= form.text_field :description %></p>
    <p>Телефон<%= form.text_field :phone %></p>
    <p>Почта<%= form.text_field :email %></p>
    <p>Веб-сайт<%= form.text_field :website %></p>
    <p>Название организации<%= form.text_field :organization_name %></p>
    <%= form.submit %>
  <% end %>
</div>

app/views/companies/index.html.erb
<div class="form-wrapper">
  <form action="<%= companies_path %>" method="get">
    <%= text_field_tag :q, params[:q], placeholder: "Поиск по компаниям"  %>
    <%= submit_tag "Поиск", :name => nil %>
  </form>
  <%= link_to 'Очистить', companies_path %>
</div>
<h1>Все компании</h1>
<% @companies.each do |company| %>
  <div class="card" style="width: 24.5rem;">
    <div class="card-body">
      <p class="card-text"><%= link_to company.name,company_path(company)%></p>
      <p class="card-text">Год основания: <%= company.foundation_year%></p>
    </div>
  </div>
<% end %>
<div class="pagination justify-content-center">
  <%= will_paginate @companies,renderer:  WillPaginate::ActionView::BootstrapLinkRenderer,previous_label: '<',next_label: '>',inner_window: 1,outer_window:0%>
</div>

app/views/companies/new.html.erb
<div class="form-style-8">
  <h2>Добавить новую компанию</h2>
  <%= form_for :company, url: new_company_path do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Год основания<%= form.text_field :foundation_year %></p>
    <p>Описание<%= form.text_field :description %></p>
    <p>Телефон<%= form.text_field :phone %></p>
    <p>Почта<%= form.text_field :email %></p>
    <p>Веб-сайт<%= form.text_field :website %></p>
    <p>Название организации<%= form.text_field :organization_name %></p>
    <%= form.submit "Создать компанию" %>
  <% end %>
</div>

app/views/companies/show.html.erb
<p> </p>
<div class="card" style="width: 30.5rem;">
  <div class="card-body">
    <h4 class="card-title"><%= @company.name%></h4>
    <p class="card-text"><%= @company.description %></p>
    <p class="card-text">Год основания: <%= @company.foundation_year.to_s %></p>
    <p class="card-text">Телефон компании: +<%= @company.phone.to_s %></p>
    <p class="card-text">Почта компании: <%= @company.email %></p>
    <p class="card-text">Организация: <%= @company.organization_name %></p>
    <p class="card-text">Веб-сайт: <%= @company.website %></p>
    <% if current_user %>
      <a href="<%= edit_company_url(@company.id) %>" class="card-link">Edit</a>
      <a class="card-link"><%= link_to  "Delete", company_path(@company.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить компанию?'} %></a>
    <% end %>
  </div>
</div>
<p> </p>
<h4 class="cntrd">Все курсы компании</h4>
<% @company_courses.each do |f| %>
  <div class="card" style="width: 24.5rem;">
    <div class="card-body">
      <p class="card-text"><%= link_to f.name,course_path(f)%></p>
      <p class="card-text">Цена: <%= f.price%>₽</p>
    </div>
  </div>
<% end %>

app/views/languages/edit.html.erb
<div class="form-style-8">
  <h2>Редактировать продукт</h2>
  <%= form_for(@language)do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Описание<%= form.text_field :description %></p>
    <%= form.submit %>
  <% end %>
</div>

app/views/languages/index.html.erb
<h1>Все продукты</h1>
<% @languages.each do |language| %>
  <div class="card" style="width: 24.5rem;">
    <div class="card-body">
      <p class="card-text"><%= link_to language.name,language_path(language)%></p>
      <p class="card-text"><%= language.description%></p>
    </div>
  </div>
<% end %>

app/views/languages/new.html.erb
<div class="form-style-8">
  <h2>Создать новый продукт</h2>
  <%= form_for :language, url: new_language_path do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Описание<%= form.text_field :description %></p>
    <%= form.submit "Создать продукт"%>
  <% end %>
</div>

app/views/languages/show.html.erb
<p> </p>
<div class="card" style="width: 24.5rem;">
  <div class="card-body">
    <h4 class="card-title">О продукте</h4>
    <p class="card-text">Продукт: <%= @language.name%></p>
    <p class="card-text">О продукте: <%= @language.description%></p>
    <% if current_user %>
      <a href="<%= edit_language_path(@language.id) %>" class="card-link">Edit</a>
      <a class="card-link"><%= link_to  "Delete", language_path(@language.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить продукт?'} %></a>
    <% end %>
  </div>
</div>
<p> </p>

app/views/subjects/edit.html.erb
<div class="form-style-8">
  <h2>Редактировать направление</h2>
  <%= form_for(@subject)do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Описание<%= form.text_field :description %></p>
    <p>Фотография</p>
    <p><%= form.file_field :avatar %></p>
    <%= form.submit %>
  <% end %>
</div>

app/views/subjects/home.html.erb
<h1>Home page of project.</h1>

app/views/subjects/index.html.erb
<div class="form-wrapper">
  <form action="<%= subjects_path %>" method="get">
    <%= text_field_tag :q, params[:q], placeholder: "Поиск по направлениям"  %>
    <%= submit_tag "Поиск", :name => nil %>
  </form>
  <%= link_to 'Очистить', subjects_path %>
</div>
<h1>Все направления</h1>
<% @subjects.each do |subject| %>
  <div class="card" style="width: 24.5rem;">
    <div class="card-body">
      <p class="card-text"><%= link_to subject.name,subject_path(subject)%></p>
      <p class="card-text"><%= subject.description%></p>
    </div>
  </div>
<% end %>
<div class="pagination justify-content-center">
  <%= will_paginate @subjects,renderer:  WillPaginate::ActionView::BootstrapLinkRenderer,previous_label: '<',next_label: '>',inner_window: 1,outer_window:0%>
</div>

app/views/subjects/new.html.erb
<div class="form-style-8">
  <h2>Создать новое направление</h2>
  <%= form_for :subject, url: new_subject_path do |form| %>
    <p>Название<%= form.text_field :name %></p>
    <p>Описание<%= form.text_field :description %></p>
    <p>Фотография</p>
    <p><%= form.file_field :avatar %></p>
    <%= form.submit "Создать направление" %>
  <% end %>
</div>

app/views/subjects/show.html.erb
<p> </p>
<div class="card" style="width: 24.5rem;">
  <div class="card-body">
    <h4 class="card-title">О направлении</h4>
    <p class="card-text"><%= image_tag @subject.avatar.url(:default) %></p>
    <p class="card-text">Направление: <%= @subject.name%></p>
    <p class="card-text">О направлении: <%= @subject.description%></p>
    <% if current_user %>
      <a href="<%= edit_subject_path(@subject.id) %>" class="card-link">Edit</a>
      <a class="card-link"><%= link_to  "Delete", subject_path(@subject.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить направление?'} %></a>
    <% end %>
  </div>
</div>
<p> </p>
<h4 class="cntrd">Все курсы по этому направлению</h4>
<% @subject_courses.each do |f| %>
  <div class="card" style="width: 24.5rem;">
    <div class="card-body">
      <p class="card-text"><%= link_to f.name,course_path(f)%></p>
      <p class="card-text">Цена: <%= f.price%>₽</p>
    </div>
  </div>
<% end %>