config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies, :subjects, :courses, :languages
  post 'subjects/new',to: 'subjects#create'
  post 'courses/new',to: 'courses#create'
  post 'companies/new',to: 'companies#create'
  post 'languages/new',to: 'languages#create'
  get "/:page" => "static#show"

  root 'subjects#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :courses
end

app/models/city.rb
class City < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  include PgSearch
  has_many :courses
  validates :name, presence: true
  #validates :rank, numericality: { only_integer: true, greater_than: 0}
  pg_search_scope :search_by_name, against: [:name, :organization_name]
end

app/models/course.rb
class Course < ApplicationRecord
  include PgSearch
  validates :name, presence: true
  validates :info, presence: true
  validates :info, length: {minimum: 15}
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  #validates :rating, numericality: {  greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  belongs_to :company
  belongs_to :subject
  has_and_belongs_to_many :languages
  pg_search_scope :search_by_name, against: [:name]
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
end

app/models/subject.rb
class Subject < ApplicationRecord
  include PgSearch
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
  has_many :courses
  has_attached_file :avatar, styles: { default: "350x300>",logo: "50x50"}, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  pg_search_scope :search_by_name, against: [:name]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index]
  def create
    @company = Company.new(company_params)
    @company.save
    if @company.errors.any?
      render :'companies/new'
    else
      redirect_to @company
    end
  end

  def new
    @company = Company.new
  end
  def index
    if params[:q] != nil
      @companies = Company.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
    else
      @companies = Company.all.paginate(:page => params[:page],per_page:4)
    end
  end
  def show
    @company = Company.find_by(id: params[:id])
    @company_courses = Course.where(company_id: [@company.id])
    if @company.nil?
      redirect_to root_path
    end
  end
  def edit
    @company = Company.find(params[:id])
  end
  def update
    @company = Company.update(params[:id],company_params)
    @company.save
    if @company.errors.any?
      render 'edit'
    else
      redirect_to company_path
    end
  end
  def delete
    @company = Company.find(params[:id])
  end
  def destroy
    Company.find(params[:id]).destroy
    redirect_to companies_path
  end
  private
    def company_params
      params.require(:company).permit(:name,:foundation_year,:description,:phone,:email,:organization_name,:website)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index]
  def create
    @course = Course.new(course_params)
    @course.save
    if @course.errors.any?
      render :'courses/new'
    else
      redirect_to @course
    end
  end

  def new
    @course = Course.new
  end
  def index
    if params[:q]
      @courses = Course.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
    else
      @courses = Course.all.paginate(:page => params[:page],per_page:1)
    end
  end
  def show
    @course = Course.find_by(id: params[:id])
    if @course.nil?
      redirect_to courses_path
    end
  end
  def edit
    @course = Course.find(params[:id])
  end
  def update
    @course = Course.update(params[:id],course_params)
    @course.save
    if @course.errors.any?
      render 'edit'
    else
      redirect_to course_path
    end
  end
  def delete
    @course = Course.find(params[:id])
  end
  def destroy
    Course.find(params[:id]).destroy
    redirect_to courses_path
  end
  private
    def course_params
    params.require(:course).permit(:name,:info,:price,:total_lessons,:company_id,:subject_id,:language_ids)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!,except: [:show,:index,:home]
    def create
      @subject = Subject.new(subject_params)
      @subject.save
      if @subject.errors.any?
        render 'new'
      else
        redirect_to @subject
      end
    end

    def new
      @subject = Subject.new
    end
    def index
      if params[:q] != nil
        @subjects = Subject.search_by_name(params[:q]).paginate(:page => params[:page],per_page:4)
      else
        @subjects = Subject.all.paginate(:page => params[:page],per_page:1)
      end
    end
    def show
      @subject = Subject.find_by(id: params[:id])
      @subject_courses = Course.where(subject_id: [@subject.id])
      if @subject.nil?
        redirect_to root_path
      end
    end
    def edit
      @subject = Subject.find(params[:id])
    end
    def update
      @subject = Subject.update(params[:id],subject_params)
      @subject.save
      if @subject.errors.any?
        render 'edit'
      else
        redirect_to subjects_path
      end
    end
    def delete
      @subject = Subject.find(params[:id])
    end
    def destroy
      Subject.find(params[:id]).destroy
      redirect_to subjects_path
    end
    private
      def subject_params
      params.require(:subject).permit(:avatar,:name,:description)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>IT-Services</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path%>"><%= image_tag "home.png"%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="<%=subjects_path%>">Все направления</a>
        <a class="nav-item nav-link" href="<%=courses_path%>">Все курсы</a>
        <a class="nav-item nav-link" href="<%=companies_path%>">Все компании</a>
        <a class="nav-item nav-link" href="<%=languages_path%>">Все продукты</a>
        <% if current_user %>
          <a class="nav-item nav-link" href="<%=new_subject_path%>">Новое направление</a>
          <a class="nav-item nav-link" href="<%=new_course_path%>">Новый курс</a>
          <a class="nav-item nav-link" href="<%=new_company_path%>">Новая компания</a>
          <a class="nav-item nav-link" href="<%=new_language_path%>">Новый продукт</a>
          <a class="nav-item nav-link" href="/about">О проекте</a>
          <a class="nav-item nav-link" <%=link_to 'Выйти', destroy_user_session_path,method: :delete %></a>
        <% else %>
          <a class="nav-item nav-link" href="/about">О проекте</a>
          <a class="nav-item nav-link" href="/users/sign_in">Войти</a>
          <a class="nav-item nav-link" href="/users/sign_up">Зарегистрироваться</a>
        <% end %>
      </div>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <%= render 'layouts/alerts' %>
  <%= yield %>

  </body>
</html>